### ISSUE TITLE
Autocompletion inserts a space between # and word

### ISSUE THREAD

**Issue by marmotton** [vanadium23/markdown-hashtags#12]
When I type '#', the autocomplete list appears and I can choose a word. When pressing 'enter', it will insert a space followed by the word. This will result in e.g. `# programming` instead of `#programming`.

In fact the space is already contained in the list, just before the word.

I saw this behavior appear in version 1.1.1.

Version 1.1.1 (note the space before the word):
![image](https://user-images.githubusercontent.com/24893706/105688772-46f18380-5efa-11eb-8312-29a1c2684290.png)

Version 1.1.0:
![image](https://user-images.githubusercontent.com/24893706/105688828-596bbd00-5efa-11eb-856e-a0793ebc0c93.png)

I'm using VSCode 1.52.1 on Linux (Ubuntu 20.10).

**Comment by ww7** [comment]
Also on macOS.

**Comment by vanadium23** [comment]
Released 1.2.1 version to fix issue.

**Comment by marmotton** [comment]
Works great, thanks !!
