### ISSUE TITLE
Exclude "#text" from tags if it's part of Code Block and #tag<symbols>

### ISSUE THREAD

**Issue by ww7** [vanadium23/markdown-hashtags#13]
1) I found many wrong tags in my markdown notes in Code Blocks, where comments parsed as tags
Please exclude parsing where  "\``` some text with new lines \```"
(Between ```)

2) Wrong tags and autocompletion for strings like #text#text, #text\<puntuation or symbols\>text, text#text
I see logic of tag detection as
if `no symbols before #` and `any letters and numbers after #` and `space or new-line at the end`

**Comment by vanadium23** [comment]
I need to parse AST for markdwon to add point 1 for excluding for autocompletion.
For second bullet, I've have issue #2. :)

**Comment by ww7** [comment]
Hi, please remove from tag suggestion case when ## or more `#` involved

**Comment by vanadium23** [comment]
I've published version 1.3.1, where the plugin doesn't autocomplete on ## and #text#text examples.

**Comment by vanadium23** [comment]
@ez4gis yes, let's open separate issue. This one was done in #22.
