### ISSUE TITLE
Wrong counting of hashtags

### ISSUE THREAD

**Issue by kasamy** [vanadium23/markdown-hashtags#15]
When open a vscode with chosen project directory then open hashtag in hashtag tree then click от the filename *.md that contain a hashtag then type space anywhere in the file it follow wrong counting of a  hashtag.

![GIF 03 06 2021 21-34-37](https://user-images.githubusercontent.com/3211143/120632200-6dc95300-c4b4-11eb-8b93-8f66a5f4ba1a.gif)

**Comment by vanadium23** [comment]
Hi, @kasamy.
I would try to rewrite logic to Set for handling unique hashtags per location.

**Comment by Decmoe47** [comment]
Just change the `path` property to `fsPath` in below line.
https://github.com/vanadium23/markdown-hashtags/blob/0d648e34183518ba17d35580fc551970d48b368a/src/parser.ts#L27
```typescript
promises.push(parseFile(file.fsPath));
```

<br>

The first time to call `getTagTree()` using the `path`property by default, while after then it uses the `fsPath` property: 
https://github.com/vanadium23/markdown-hashtags/blob/0d648e34183518ba17d35580fc551970d48b368a/src/extension.ts#L20-L21
The difference can be found in [vscode api reference](https://code.visualstudio.com/api/references/vscode-api#Uri).
![image](https://user-images.githubusercontent.com/55980717/176427519-9007678a-ca32-4b16-902c-66ad8565fd71.png)

**Comment by vanadium23** [comment]
Closed via #22
