### ISSUE TITLE
Allow configuration of file extensions to be supported (goal: .adoc)

### ISSUE THREAD

**Issue by aisbergde** [vanadium23/markdown-hashtags#21]
I converted my notes system from markdown to AsciiDoc. It looks like the extension works fine on my old notes written in markdown and containing some hash tags, but `.adoc` is not supported.

Is it possible to also scan `.adoc` files in general or to add a configuration, where a user can add additional file extensions?

**Comment by aisbergde** [comment]
I would say, it is solved. Because I can use "markdown-hashtags.file_extensions"

**Comment by vanadium23** [comment]
Great 👍
