### ISSUE TITLE
Alternative nested tags with dot, additionally to slash

### ISSUE THREAD

**Issue by aisbergde** [vanadium23/markdown-hashtags#24]
It would be good if you could also use dots / points to separate the hierarchies. Maybe via further settings.

Maybe this rule could be changed? Maybe via settings?

____
the hashtag path is cut off at a whitespace or a punctuation including +
`!@#$%^&*()=+.,[];:'"?><`.
____

My goal is a virtual file system that follows this idea of hierarchical notes: 

https://wiki.dendron.so/notes/f3a41725-c5e5-4851-a6ed-5f541054d409/#whats-with-the-s

Because a file has only one (1) filename like

`project1.area1.item1.adoc`

But the file can optionally get additional virtual filenames via tags. The result would be something similar to symbolic links.

```
#item1.project1
#item1/project1
// #project2.area3.item1
// #project2/area3/item1
// #definition.item1
// #definition/item1
```

**Comment by aisbergde** [comment]
@vanadium23 would it be OK, if I learn TypoScript and implement this feature?

**Comment by vanadium23** [comment]
@aisbergde yeah, it will be awesome.

**Comment by aisbergde** [comment]
is there a chance to use the pull request #24?
