### ISSUE TITLE
Add config for sorting option in hashtag panel

### ISSUE THREAD

**Issue by vanadium23** [vanadium23/markdown-hashtags#4]
Options to sort: alphabetical asc/desc, count asc/desc

**Comment by jowitte** [comment]
This would actually help.

**Comment by martinandersen3d** [comment]
quickfix: default to asc ? :-)

**Comment by vanadium23** [comment]
Hello, fellows.
I've released 1.3.0 version and add two sorting options to config.

**Comment by jowitte** [comment]
Awesome. Thanks a lot!
