### ISSUE TITLE
Support unicode hashtag please

### ISSUE THREAD

**Issue by LambdaAlpha** [vanadium23/markdown-hashtags#5]
I tried this extension and found that it didn't support unicode hashtag. Tags like "#标签" are not listed in hashtag tree.

**Comment by LambdaAlpha** [comment]
Maybe we can change `"match": "(^|\\s)(\\#[\\w\\p{L}\\-\\_]+)"` to `"match": "(^|\\s)(\\#[^\\s\\#]+)"` or sth like that.

**Comment by vanadium23** [comment]
Good suggestion, I'll try to find regexp.
Thank you :)

**Comment by vanadium23** [comment]
I've pushed new version to the marketplace.
